"""add field to food-category model

Revision ID: 424391c806ce
Revises: d669f95aa6a2
Create Date: 2026-03-07 20:40:02.561208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424391c806ce'
down_revision: Union[str, Sequence[str], None] = 'd669f95aa6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_categories', sa.Column('ml_category', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_categories', 'ml_category')
    # ### end Alembic commands ###
