"""link image model to user model

Revision ID: 4c9f25abae76
Revises: 2c53467edabe
Create Date: 2026-01-24 21:25:40.270190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9f25abae76'
down_revision: Union[str, Sequence[str], None] = '2c53467edabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('images_user_id_fkey'), 'images', type_='foreignkey')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('images_user_id_fkey'), 'images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
