"""init

Revision ID: 9c182a208f95
Revises: 7932bfe78a95
Create Date: 2026-01-22 18:00:29.860670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c182a208f95'
down_revision: Union[str, Sequence[str], None] = '7932bfe78a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('storage_tips', sa.Text(), nullable=True))
    op.add_column('shopping_list_items', sa.Column('default_shelf_life_day', sa.Integer(), nullable=True))
    op.drop_column('shopping_list_items', 'default_shelf_life_day_snapshot')
    op.drop_column('shopping_list_items', 'storage_tips_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('storage_tips_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('shopping_list_items', sa.Column('default_shelf_life_day_snapshot', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('shopping_list_items', 'default_shelf_life_day')
    op.drop_column('shopping_list_items', 'storage_tips')
    # ### end Alembic commands ###
