"""link image model to user model

Revision ID: ab4292334c03
Revises: a12b1a724356
Create Date: 2026-01-24 21:42:54.770788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4292334c03'
down_revision: Union[str, Sequence[str], None] = 'a12b1a724356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('shopping_list_item_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'images', 'shopping_list_items', ['shopping_list_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'shopping_list_item_id')
    # ### end Alembic commands ###
