// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfFCWLGAa-fHRYi3a44y5DKVqbjiwUvw8',
    appId: '1:999245067102:web:4c0d8f69ee3872e86795cf',
    messagingSenderId: '999245067102',
    projectId: 'kirito-project-35852',
    authDomain: 'kirito-project-35852.firebaseapp.com',
    storageBucket: 'kirito-project-35852.firebasestorage.app',
    measurementId: 'G-TZ29WYYVQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlCzkYqYOAJHEXCMbM_VSvLVsXH26g6Wk',
    appId: '1:999245067102:android:a8f0a515cef78cc46795cf',
    messagingSenderId: '999245067102',
    projectId: 'kirito-project-35852',
    storageBucket: 'kirito-project-35852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOHnmOio6T1PdRVhycfKuEmYlB9yj6o9I',
    appId: '1:999245067102:ios:c571d01e3bdba6ef6795cf',
    messagingSenderId: '999245067102',
    projectId: 'kirito-project-35852',
    storageBucket: 'kirito-project-35852.firebasestorage.app',
    iosBundleId: 'com.example.gaspikaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOHnmOio6T1PdRVhycfKuEmYlB9yj6o9I',
    appId: '1:999245067102:ios:c571d01e3bdba6ef6795cf',
    messagingSenderId: '999245067102',
    projectId: 'kirito-project-35852',
    storageBucket: 'kirito-project-35852.firebasestorage.app',
    iosBundleId: 'com.example.gaspikaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt_QFFQBgbYj61C4OEb7fIByE6Xl9FQ4g',
    appId: '1:999245067102:web:fe38a9038fe024e06795cf',
    messagingSenderId: '999245067102',
    projectId: 'kirito-project-35852',
    authDomain: 'kirito-project-35852.firebaseapp.com',
    storageBucket: 'kirito-project-35852.firebasestorage.app',
    measurementId: 'G-7XKWW921FM',
  );
}
